name: changelog-update

on:
  release:
    types: [released]

jobs:
  update:
    uses: shishifubing/ci-actions-common/.github/workflows/changelog-update.yml@a8a103959a5947d3914ceb6b779ecc982dff62b8 # v0.1.30
    secrets: inherit
