name: tag

on:
  push:
    paths-ignore:
      - README.md
      - docs/**
      - .github/**/*.md
      - .github/FUNDING.yml
      - .github/ISSUE_TEMPLATE/**
    branches:
      - main

jobs:
  tag:
    uses: shishifubing/ci-actions-common/.github/workflows/tag.yml@main
    secrets: inherit
