name: Tag

on:
  pull_request:
  push:
    branches:
      - main

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  tag:
    name: Create a tag after PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Download gitversion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: 5.x

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Import bot's GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Tag
        env:
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
        run: |
          tag="v$(gitversion -showvariable SemVer)"
          commits="${{ steps.gitversions.outputs.commitsSinceVersionSource }}"
          format_commit='format:- %s%n  %b%n%n  %H'
          format_merge='format:# %s%n%b'
          merge_commit=$(git log -n 1 --pretty="${format_merge}")
          message=$(git log -n "${commits}" --skip=1 --pretty="${format_commit}")

          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
