name: Tag

on:
  pull_request:
  push:
    branches:
      - main

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  tag:
    name: Create a tag after PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPO }}

      - name: Download gitversion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: 5.x

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Tag
        run: |
          tag="v${{ steps.gitversion.outputs.semVer }}"
          git tag "${tag}"
          git push origin "${tag}"
