name: Create a tag

on:
  push:
    paths-ignore:
      - README.md
      - docs/**
      - .github/**/*.md
      - .github/FUNDING.yml
      - .github/ISSUE_TEMPLATE/**
    branches:
      - main

jobs:
  tag:
    name: Call a workflow
    uses: shishifubing/ci-actions-common/.github/workflows/tag.yml@main
    secrets:
      ci_github_token: ${{ secrets.CI_GITHUB_TOKEN }}
      gpg_private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
